### ISSUE TITLE
build #41 crashes on my phone

### ISSUE THREAD

**Issue by galsuchetzky** [kivymd/KitchenSink#2]
Downloaded build #41 and installed on my phone, it crashes.
my phone is Samsung Note 9

**Comment by EvgeniyGolovin** [comment]
build #44

11-27 14:08:02.043 16593 16644 I python  : [ERROR  ] [Clock       ] Unable to import kivy._clock. Have you perhaps forgotten to compile kivy? Kivy contains Cython code which needs to be compiled. A missing kivy._clock often indicates the Cython code has not been compiled. Please follow the installation instructions and make sure to compile Kivy
11-27 14:08:02.043 16593 16644 I python  :  Traceback (most recent call last):
11-27 14:08:02.043 16593 16644 I python  :    File "/home/llynx/Desktop/KitchenSink/KitchenSink/.buildozer/android/app/main.py", line 5, in <module>
11-27 14:08:02.043 16593 16644 I python  :    File "/home/llynx/Desktop/KitchenSink/KitchenSink/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/kitchensink/armeabi-v7a/kivy/core/window/__init__.py", line 18, in <module>
11-27 14:08:02.043 16593 16644 I python  :    File "/home/llynx/Desktop/KitchenSink/KitchenSink/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/kitchensink/armeabi-v7a/kivy/clock.py", line 466, in <module>
11-27 14:08:02.044 16593 16644 I python  :  ImportError: dlopen failed: "/data/data/org.kivymd.kitchensink/files/app/_python_bundle/site-packages/kivy/_clock.so" is 64-bit instead of 32-bit
11-27 14:08:02.044 16593 16644 I python  : Python for android ended.

**Comment by c4pointer** [comment]
i have also the problem with build #45 at start on my phone Huawei p40 lite

**Comment by Akul2010** [comment]
I'm using Samsung S21, I found no problem.

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KitchenSink/commit/35f0ec61c79071d310e7f88dcdd982d49d6ba53a
